<?php

return [
    'CasaRosa' => 'Casa Rosa',
    'CasaVerde' => 'Casa Verde',
    'cliccaQuiVerde' => 'Clicca qui per maggiori info sulla Casa Verde',
    'LAppartamentoVerde' => "L'appartamento, di recentissima costruzione e caratterizzato da colori caldi, offre un ambiente accogliente e confortevole. La cucina è completamente attrezzata con piano cottura ad induzione e dispone di tutti gli utensili necessari (pentole, bicchieri, piatti, bollitore, macchinetta del caffè e moka, ecc.), oltre a un frigorifero con congelatore. La cucina si fonde armoniosamente con il soggiorno, creando uno spazio unico. Nel soggiorno, troverai un televisore su un mobile, dotato di una cassetta di sicurezza e spazio aggiuntivo per riporre le tue cose. Accanto al televisore, c'è un comodo divano che, di sera, può essere trasformato in un pratico divano letto matrimoniale. Un tavolo da pranzo poco distante dalla finestra, che offre una vista sul belvedere dove le persone passeggiano, mentre sotto si trova un condizionatore per mantenere un clima piacevole. La zona giorno è separata dalla stanza da letto insonorizzata, che dispone di un letto matrimoniale con doppio cuscino (memory e uno più sottile, per soddisfare qualsiasi esigenza), un bagno privato e una finestra, anch'essa dotata di condizionatore per un comfort ottimale.",
    'chiudi' => 'chiudi',
    'cliccaQuiRosa' => 'Clicca qui per maggiori info sulla Casa Rosa',
    'LAppartamentoRosa' => "Varcando la soglia di questa splendida abitazione, si viene accolti da una freschezza avvolgente che permea l'ambiente. Un divano rosa, dal design minimalista ma sofisticato, cattura subito l'attenzione, affiancato da una televisione posizionata strategicamente per essere comodamente visibile sia dal divano che dal tavolo da pranzo adiacente. Di fronte al tavolo, la cucina si fonde armoniosamente con le pareti, dotata di piano cottura ad induzione e di ogni accessorio immaginabile, inclusi bollitore e la possibilità di scegliere tra macchina da caffè a cialde o moka. Una grande finestra di fronte alla cucina offre una vista incantevole sul mare e sul vivace centro cittadino. Sul lato opposto del divano, un muro scorrevole nasconde una lavatrice e gli strumenti per la casa, mentre la porta per accedere alla prima camera da letto si frappone fra il divano e il muro. Questa camera è ariosa, spaziosa e luminosa, con un balconcino che diffonde una luce delicata che si sposa armoniosamente con i toni rosa della casa e dei quadri sopra il letto matrimoniale. Una televisione a muro completa il comfort della stanza. L'armadio, ingegnosamente progettato, include anche un pratico portavaligie. La stanza ha anche un bagno privato completo di doccia, bidet, wc e lavandino. La seconda stanza è raggiungibile attraverso un corridoio, dove si trova un armadio, una cassetta di sicurezza e un magazzino fornito di tutti gli attrezzi necessari per la casa. Anche questa stanza è dotata di una TV a muro, una finestra e un letto matrimoniale. La testata del letto si trasforma in un innovativo mobiletto dove riporre cuscini e coperte, offrendo un tocco di ingegnosità e praticità.",
    'footerRosa' => "Varcando la soglia di questa splendida abitazione, si viene accolti da una freschezza avvolgente che permea l'ambiente. Un divano rosa, dal design minimalista ma sofisticato, cattura subito l'attenzione, affiancato da una televisione posizionata strategicamente per essere comodamente visibile sia dal divano che dal tavolo da pranzo adiacente. Di fronte al tavolo, la cucina si fonde armoniosamente con le pareti, dotata di piano cottura ad induzione e di ogni accessorio immaginabile, inclusi bollitore e la possibilità di scegliere tra macchina da caffè a cialde o moka. Una grande finestra di fronte alla cucina offre una vista incantevole sul mare e sul vivace centro cittadino. Sul lato opposto del divano, un muro scorrevole nasconde una lavatrice e gli strumenti per la casa, mentre la porta per accedere alla prima camera da letto si frappone fra il divano e il muro. Questa camera è ariosa, spaziosa e luminosa, con un balconcino che diffonde una luce delicata che si sposa armoniosamente con i toni rosa della casa e dei quadri sopra il letto matrimoniale. Una televisione a muro completa il comfort della stanza. L'armadio, ingegnosamente progettato, include anche un pratico portavaligie. La stanza ha anche un bagno privato completo di doccia, bidet, wc e lavandino. La seconda stanza è raggiungibile attraverso un corridoio, dove si trova un armadio, una cassetta di sicurezza e un magazzino fornito di tutti gli attrezzi necessari per la casa. Anche questa stanza è dotata di una TV a muro, una finestra e un letto matrimoniale. La testata del letto si trasforma in un innovativo mobiletto dove riporre cuscini e coperte, offrendo un tocco di ingegnosità e praticità.",
    'footerVerde' => "L'appartamento, di recentissima costruzione e caratterizzato da colori caldi, offre un ambiente accogliente e confortevole. La cucina è completamente attrezzata con piano cottura ad induzione e dispone di tutti gli utensili necessari (pentole, bicchieri, piatti, bollitore, macchinetta del caffè e moka, ecc.), oltre a un frigorifero con congelatore. La cucina si fonde armoniosamente con il soggiorno, creando uno spazio unico. Nel soggiorno, troverai un televisore su un mobile, dotato di una cassetta di sicurezza e spazio aggiuntivo per riporre le tue cose. Accanto al televisore, c'è un comodo divano che, di sera, può essere trasformato in un pratico divano letto matrimoniale. Un tavolo da pranzo poco distante dalla finestra, che offre una vista sul belvedere dove le persone passeggiano, mentre sotto si trova un condizionatore per mantenere un clima piacevole. La zona giorno è separata dalla stanza da letto insonorizzata, che dispone di un letto matrimoniale con doppio cuscino (memory e uno più sottile, per soddisfare qualsiasi esigenza), un bagno privato e una finestra, anch'essa dotata di condizionatore per un comfort ottimale.",
    



];