<?php

return [
    'CasaRosa' => 'Pink House',
    'CasaVerde' => 'Green House',
    'cliccaQuiVerde' => 'Click here for more info on the Green House',
    'LAppartamentoVerde' => "The apartment, recently built and characterized by warm colors, offers a welcoming and comfortable environment. The kitchen is fully equipped with an induction hob and has all the necessary utensils (pots, glasses, plates, kettle, coffee machine and moka pot, etc.), as well as a refrigerator with freezer. The kitchen harmoniously merges with the living room, creating a unique space. In the living room, you will find a television on a stand, equipped with a safety deposit box and additional space to store your belongings. Next to the television, there is a comfortable sofa which, in the evening, can be transformed into a practical double sofa bed. A dining table is located not far from the window, providing a view of the overlook where people stroll, while below there is an air conditioner to maintain a pleasant climate. The living area is separated from the soundproofed bedroom, which features a double bed with dual pillows (memory foam and a thinner one, to meet any need), a private bathroom, and a window, also equipped with an air conditioner for optimal comfort.",
    'chiudi' => 'close',
    'cliccaQuiRosa' => 'Click here for more info on the Pink house',
    'LAppartamentoRosa' => "Stepping through the threshold of this stunning abode, one is greeted by a refreshing ambience that permeates the space. A minimalist yet sophisticated pink sofa immediately captures attention, flanked by a strategically positioned television visible from both the sofa and the adjacent dining table. Facing the table, the kitchen seamlessly blends with the walls, equipped with an induction hob and every imaginable accessory, including a kettle and the option to choose between a capsule coffee machine or a moka pot. A large window in front of the kitchen offers a charming view of the sea and the lively city center. On the opposite side of the sofa, a sliding wall conceals a washing machine and household tools, while the door to access the first bedroom is nestled between the sofa and the wall. This bedroom is airy, spacious, and bright, with a balcony that diffuses a gentle light harmoniously blending with the pink tones of the house and the artwork above the double bed. A wall-mounted television completes the comfort of the room. The ingeniously designed wardrobe also includes a handy luggage rack. The room also features a private bathroom complete with shower, bidet, toilet, and sink. The second room is accessible through a corridor, where a wardrobe, a safety deposit box, and a storage room stocked with all necessary household tools are found. This room also boasts a wall-mounted TV, a window, and a double bed. The bed's headboard transforms into an innovative cabinet to store pillows and blankets, offering a touch of ingenuity and practicality.",
    'footerRosa' => "Stepping through the threshold of this stunning abode, one is greeted by a refreshing ambience that permeates the space. A minimalist yet sophisticated pink sofa immediately captures attention, flanked by a strategically positioned television visible from both the sofa and the adjacent dining table. Facing the table, the kitchen seamlessly blends with the walls, equipped with an induction hob and every imaginable accessory, including a kettle and the option to choose between a capsule coffee machine or a moka pot. A large window in front of the kitchen offers a charming view of the sea and the lively city center. On the opposite side of the sofa, a sliding wall conceals a washing machine and household tools, while the door to access the first bedroom is nestled between the sofa and the wall. This bedroom is airy, spacious, and bright, with a balcony that diffuses a gentle light harmoniously blending with the pink tones of the house and the artwork above the double bed. A wall-mounted television completes the comfort of the room. The ingeniously designed wardrobe also includes a handy luggage rack. The room also features a private bathroom complete with shower, bidet, toilet, and sink. The second room is accessible through a corridor, where a wardrobe, a safety deposit box, and a storage room stocked with all necessary household tools are found. This room also boasts a wall-mounted TV, a window, and a double bed. The bed's headboard transforms into an innovative cabinet to store pillows and blankets, offering a touch of ingenuity and practicality.",
    'footerVerde' => "The apartment, recently built and characterized by warm colors, offers a welcoming and comfortable environment. The kitchen is fully equipped with an induction hob and has all the necessary utensils (pots, glasses, plates, kettle, coffee machine and moka pot, etc.), as well as a refrigerator with freezer. The kitchen harmoniously merges with the living room, creating a unique space. In the living room, you will find a television on a stand, equipped with a safety deposit box and additional space to store your belongings. Next to the television, there is a comfortable sofa which, in the evening, can be transformed into a practical double sofa bed. A dining table is located not far from the window, providing a view of the overlook where people stroll, while below there is an air conditioner to maintain a pleasant climate. The living area is separated from the soundproofed bedroom, which features a double bed with dual pillows (memory foam and a thinner one, to meet any need), a private bathroom, and a window, also equipped with an air conditioner for optimal comfort.",
    
];